#!/usr/bin/env bash
# =============================================================================
# Oracle Cloud Always Free — one-time provisioning script for The Healing
# Presence Spring Boot app.
#
# Target: a fresh Ubuntu 22.04 Ampere A1 VM (created via Oracle Cloud free tier).
# Installs: Eclipse Temurin JDK 21, MySQL 8, Caddy (HTTPS reverse proxy).
# Sets up: `thp` system user, /opt/healingpresence dirs, systemd service,
#          ufw firewall (22, 80, 443), MySQL DB + app user.
#
# USAGE (on the VM, as a sudoer):
#   curl -sLO https://raw.githubusercontent.com/kaivalyaekaa/The-Healing-Presence/jsp-rebuild/deploy/setup-oracle.sh
#   chmod +x setup-oracle.sh
#   sudo bash setup-oracle.sh
#
# After it finishes:
#   1. Edit /etc/healing-presence.env and fill in real secrets (DB_PASS, GOOGLE_*).
#   2. Upload your built WAR to /opt/healingpresence/healing-presence.war via scp.
#   3. systemctl restart healing-presence
#   4. Point your domain's A record at this VM's public IP.
# =============================================================================
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
   echo "[!] Must run as root (use sudo)." >&2
   exit 1
fi

echo "==> 1/8  Updating apt index..."
apt-get update -y

echo "==> 2/8  Installing Eclipse Temurin JDK 21..."
apt-get install -y wget apt-transport-https gnupg
wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor > /usr/share/keyrings/adoptium.gpg
echo "deb [signed-by=/usr/share/keyrings/adoptium.gpg] https://packages.adoptium.net/artifactory/deb $(lsb_release -cs) main" \
  > /etc/apt/sources.list.d/adoptium.list
apt-get update -y
apt-get install -y temurin-21-jdk

echo "==> 3/8  Installing MySQL 8..."
apt-get install -y mysql-server
systemctl enable --now mysql

echo "==> 4/8  Creating MySQL database + app user..."
DB_PASS_GENERATED="$(openssl rand -base64 18 | tr -d '/+=' | head -c 20)"
mysql -e "CREATE DATABASE IF NOT EXISTS healingpresence CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
mysql -e "CREATE USER IF NOT EXISTS 'thp_app'@'localhost' IDENTIFIED BY '${DB_PASS_GENERATED}';"
mysql -e "GRANT ALL PRIVILEGES ON healingpresence.* TO 'thp_app'@'localhost';"
mysql -e "FLUSH PRIVILEGES;"
echo "    --> MySQL user 'thp_app' created; generated password will be written to /etc/healing-presence.env"

echo "==> 5/8  Creating thp system user + /opt/healingpresence layout..."
id -u thp >/dev/null 2>&1 || useradd --system --shell /usr/sbin/nologin --home /opt/healingpresence thp
mkdir -p /opt/healingpresence
chown thp:thp /opt/healingpresence

echo "==> 6/8  Installing Caddy (auto-HTTPS reverse proxy)..."
apt-get install -y debian-keyring debian-archive-keyring
curl -1sLf https://dl.cloudsmith.io/public/caddy/stable/gpg.key \
  | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt \
  | tee /etc/apt/sources.list.d/caddy-stable.list
apt-get update -y
apt-get install -y caddy

echo "==> 7/8  Dropping in systemd unit + Caddyfile + env file..."
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# systemd unit
cp "${SCRIPT_DIR}/healing-presence.service" /etc/systemd/system/healing-presence.service

# Caddyfile (uses the public IP as a placeholder; edit to real domain later)
PUBLIC_IP="$(curl -s ifconfig.me || echo "REPLACE_ME")"
sed "s/REPLACE_DOMAIN_OR_IP/${PUBLIC_IP}.nip.io/g" "${SCRIPT_DIR}/Caddyfile" > /etc/caddy/Caddyfile

# env file
cat > /etc/healing-presence.env <<EOF
# === REVIEW + EDIT THESE BEFORE STARTING THE SERVICE ===

SPRING_PROFILES_ACTIVE=prod

# MySQL — DB_PASS was generated by setup-oracle.sh; rotate it if you want
DB_URL=jdbc:mysql://localhost:3306/healingpresence?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
DB_USER=thp_app
DB_PASS=${DB_PASS_GENERATED}

# Email (set real SMTP creds before contact-form notifications will work)
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USER=
MAIL_PASS=
APP_NOTIFY_TO=info@thehealingpresence.in
APP_NOTIFY_FROM=noreply@thehealingpresence.in

# Google Calendar (paste from Google Cloud OAuth2 client; update redirect-uri
# to your real domain before Upma signs in)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_CALENDAR_ID=primary
GOOGLE_REDIRECT_URI=https://${PUBLIC_IP}.nip.io/admin/google-calendar/callback
EOF
chmod 600 /etc/healing-presence.env
chown root:thp /etc/healing-presence.env

echo "==> 8/8  Firewall + enabling services..."
apt-get install -y ufw
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow http
ufw allow https
ufw --force enable

systemctl daemon-reload
systemctl enable caddy
systemctl restart caddy
systemctl enable healing-presence
# NOTE: don't start the service yet — wait until the WAR is uploaded.

cat <<EOF

============================================================================
 SETUP COMPLETE
============================================================================

  - VM is now reachable on:   http://${PUBLIC_IP}.nip.io
  - Caddy will provision Let's Encrypt HTTPS automatically once port 80/443
    are reachable from the public internet.

  Next steps:

  1) Upload the WAR from your laptop:
        scp target/healing-presence.war ubuntu@${PUBLIC_IP}:/tmp/
        sudo mv /tmp/healing-presence.war /opt/healingpresence/
        sudo chown thp:thp /opt/healingpresence/healing-presence.war

  2) Review and edit secrets:
        sudo nano /etc/healing-presence.env
        # Fill in MAIL_USER, MAIL_PASS, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET

  3) Start the app:
        sudo systemctl start healing-presence
        sudo systemctl status healing-presence

  4) Tail logs:
        sudo journalctl -u healing-presence -f

  5) Point thehealingpresence.in DNS A-record at this VM's IP (${PUBLIC_IP}),
     then update /etc/caddy/Caddyfile to use the real domain and reload:
        sudo systemctl reload caddy

============================================================================
EOF
